[project]
name = "charm-analysis"
version = "1.0.0b1"
description = "Tool to analyse charm code en masse"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.7",
    "httpx>=0.27.2",
    "packaging>=24.1",
    "pyyaml>=6.0.2",
    "rich>=13.8.0",
]
