[tox]
env_list = lint, test

[testenv:lint]
description = Run ruff linter and formatter checks
skip_install = true
deps =
    ruff
commands =
    ruff check --preview {posargs:.}
    ruff format --preview --check {posargs:.}

[testenv:test]
description = Run unit tests
skip_install = true
deps =
    click
    httpx
    packaging
    pyyaml
    rich
    pytest
    pytest-asyncio
commands =
    pytest {posargs:tests/}
