name: Spread Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  define-matrix:
    name: Define spread matrix
    runs-on: ubuntu-24.04
    outputs:
      suites: ${{ steps.suites.outputs.suites }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: false

      - name: Install spread
        run: |
          go install github.com/snapcore/spread/cmd/spread@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate matrix list
        id: suites
        run: |
          list="$($HOME/go/bin/spread -list github-ci | sed "s|github-ci:ubuntu-24.04:tests/spread/||g" | jq -r -ncR '[inputs | select(length>0)]')"
          echo "suites=$list"
          echo "suites=$list" >> $GITHUB_OUTPUT

  spread-test:
    name: "Spread (${{ matrix.suite }})"
    runs-on: ubuntu-24.04
    needs:
      - define-matrix
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.define-matrix.outputs.suites) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: false

      - name: Install spread
        run: |
          go install github.com/snapcore/spread/cmd/spread@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run integration tests
        env:
          SUITE: ${{ matrix.suite }}
        run: |
          $HOME/go/bin/spread -v "github-ci:ubuntu-24.04:tests/spread/${SUITE}"
